apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yourusername/librechat-gitops.git
    targetRevision: HEAD
    path: charts/ollama
    helm:
      values: |
        # Add custom values if needed
  destination:
    server: https://kubernetes.default.svc
    namespace: ollama
  syncPolicy:
    automated:
      prune: true
      selfHeal: true